title: VQA-VS
logo: VS.jpg
description: To alleviate the single-shortcut limitation and overcome three issues in practice, we construct and publicly release a new VQA benchmark considering Varying Shortcuts, named VQA-VS, and further standardize the OOD testing procedure. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
